### ISSUE TITLE
Use JSON-Schema instead of `entity_events` for event type restriction?

### ISSUE THREAD

**Issue by Ocramius** [mattbishop/sql-event-store#1]
Looking at the new postgresql (which is awesome, BTW!), I was wondering if it is feasible to use JSON-Schema to restrict the type of event being saved to the event store, checking for schema validity in an on-insert trigger: is that feasible, in your opinion? Would that remove the need for `entity_events`?

Mostly a question, not hoping for an implementation 👍

**Comment by mattbishop** [comment]
It's a great idea and I use json-schema at the application layer to validate the data in the commands and generated events. Ideally one could run a json-schema validator in the DB, as you suggest. I haven't found this capability in SQLite, but I did find this for Postgres: https://github.com/gavinwahl/postgres-json-schema

Regardless, `entity_events` is still required because the entity name and event are separate columns from the data. If anything, I would need to add a column to `entity_events` to store the relevant json-schema with which to validate the `data` field.

**Comment by Ocramius** [comment]
Was looking at the same repository.

So in practice this is feasible in postgresql by extending `entity_events` by one column, and you'd still keep that table.

Thanks for clarifying 👍

**Comment by mattbishop** [comment]
Thank you for the idea! I'll try it out and either update the DDL or report what troubles I ran into.
